### PR TITLE
/archive fixes

### LINKED ISSUE #181: Fix `/archive`
Miscellaneous fixes on `/archive`. 
image

### PR DESCRIPTION
**Pull request by Arc-blroth**
Fixes #181

### CODE REVIEW

File: data/archive.ts [hunk 1]
```diff
@@ -36,22 +38,32 @@ for (const event of eventData) {
...
       name: seriesId,
       description: eventTypes.find(x => x.name === seriesId)!.description,
       events,
     }))
   }
-})
+}).sort((a, b) => {
+  if (a.year == b.year) return SEASONS[a.season] - SEASONS[b.season];
+  return a.year - b.year;
+}).reverse();
```
Comment (Aplet123) [inline data/archive.ts:67]: Instead of `.sort().reverse()` just reverse the sort comparator

**Review by Aplet123 — APPROVED** [review]
